### PR TITLE
Adding support for Ed521.

### PR DESCRIPTION
**Pull request by LucasPenido**
Implementing Ed521.

Using params described here: [https://neuromancer.sk/std/other/E-521](https://neuromancer.sk/std/other/E-521)

### CODE REVIEW

**Comment by LucasPenido** [comment]
Ed521 Implemented.
I tested with a Digital Signature signed by the Root CA of my country.

**Review by cslashm — COMMENTED** [review]
Can you add some tests at the end of eddsa.py file?
Then it's OK, I will merge, bump the version and release on PIP depo

**Comment by LucasPenido** [comment]
Done! :+1:

**Review by cslashm — APPROVED** [review]
Seems OK.
I will merge it in the coming days.
Thanks for your PR

**Pull request merged**
