### PR TITLE
switch from setuptools to poetry

### PR DESCRIPTION
**Pull request by ledhed2222**
Heyo - I would love to eventually help you add type checking to this repo, as it will help us make the `xrpl-py` package better. As a first step, I recommend switching from `setuptools` to `poetry` as the latter makes it much easier IMO to manage development dependencies.

At the moment you have no dev dependencies, but once we add type checking etc we'll have a lot.

### CODE REVIEW

**Comment by ledhed2222** [comment]
to be clear - the ultimate goal is to add type checking to ECPy - see https://github.com/XRPLF/xrpl-py

we're using you as a dependency and it would definitely be good to add.

**Comment by ledhed2222** [comment]
ping

**Comment by cslashm** [comment]
Hi, 
Sorry, Didn't see the PR, I will review that ASAP
Thanks for your contrib (and the ping)

**Comment by cslashm** [comment]
Ok let's try it.

**Pull request merged**
